// Global Parameters Settings

#define DEFAULT_CHANNEL01_DEVICE_INDEX	0
#define DEFAULT_CHANNEL23_DEVICE_INDEX	0

#define DEFAULT_OUTPUT_SAMPLING_RATE	16000

#define STATUS_BITMAP_WIDTH		512
#define STATUS_BITMAP_HEIGHT	384
